channels:
  - conda-forge
dependencies:
  - jupyter-server-proxy>=4.3.0
  - jupyterhub-singleuser
  - websockify
  - jupytext
  - nodejs
  - mcstas=3.4.42
  - ncrystal
  - mcpl
  - nexus
  - openmpi
  - nbgitpuller
  - h5py
  - ipympl
  - ipython
  - ipywidgets
  - pythreejs
  - jupyterlab
  - python-graphviz
  - scipp::plopp
  - scipp::scipp
  - scipp::scippneutron
  - scipp::scippnexus
  - scitacean
  - mpltoolbox
  - pandas
  - pooch
  - scipy
  - numpy<2
  - emcee
  - dynesty
  - ply
  - corner
  - tqdm
  - git
  - pip
  - pip:
      - easyscience
      - McStasScript
      - jupyterquiz
