channels:
  - conda-forge
dependencies:
  - jupyter-server-proxy>=1.4
  - pip
  - websockify
  - jupytext
  - nodejs
  - mcstas=3.5.1=hce30654_1
  - mcxtrace=3.5.1=hce30654_1
  - xraylib
  - ncrystal
  - mcpl
  - nexus
  - openmpi
  - nbgitpuller
  - pip:
      - McStasScript
      - guide_bot
      - .
